"""Email formatting and sending for the story discovery briefing."""

import os
from datetime import datetime

from sendgrid import SendGridAPIClient
from sendgrid.helpers.mail import Mail, Content


def format_briefing_html(stories: list[dict]) -> str:
    """Convert story candidates into a clean HTML email."""
    date_str = datetime.now().strftime("%B %d, %Y")

    stories_html = ""
    for i, story in enumerate(stories, 1):
        sources_html = "".join(
            f'<li><a href="{s}" style="color:#2563eb;">{s}</a></li>'
            if s.startswith("http")
            else f"<li>{s}</li>"
            for s in story.get("sources", [])
        )
        experts_html = "".join(
            f"<li>{expert}</li>" for expert in story.get("who_to_talk_to", [])
        )

        stories_html += f"""
        <tr><td style="padding:32px 0 0 0;">
          <h2 style="margin:0 0 12px 0;font-size:20px;color:#111;">
            {i}. {story["headline"]}
          </h2>

          <h3 style="margin:16px 0 4px 0;font-size:14px;color:#6b7280;text-transform:uppercase;letter-spacing:0.05em;">
            The Story
          </h3>
          <p style="margin:0 0 12px 0;font-size:16px;line-height:1.6;color:#374151;">
            {story["the_story"]}
          </p>

          <h3 style="margin:16px 0 4px 0;font-size:14px;color:#6b7280;text-transform:uppercase;letter-spacing:0.05em;">
            Why Now
          </h3>
          <p style="margin:0 0 12px 0;font-size:16px;line-height:1.6;color:#374151;">
            {story["why_now"]}
          </p>

          <h3 style="margin:16px 0 4px 0;font-size:14px;color:#6b7280;text-transform:uppercase;letter-spacing:0.05em;">
            The Missing Angle
          </h3>
          <p style="margin:0 0 12px 0;font-size:16px;line-height:1.6;color:#059669;font-style:italic;">
            {story["missing_angle"]}
          </p>

          <h3 style="margin:16px 0 4px 0;font-size:14px;color:#6b7280;text-transform:uppercase;letter-spacing:0.05em;">
            Who to Talk To
          </h3>
          <ul style="margin:0 0 12px 0;padding-left:20px;font-size:15px;line-height:1.6;color:#374151;">
            {experts_html}
          </ul>

          <h3 style="margin:16px 0 4px 0;font-size:14px;color:#6b7280;text-transform:uppercase;letter-spacing:0.05em;">
            Tension / Pushback
          </h3>
          <p style="margin:0 0 12px 0;font-size:16px;line-height:1.6;color:#dc2626;">
            {story["tension_pushback"]}
          </p>

          <h3 style="margin:16px 0 4px 0;font-size:14px;color:#6b7280;text-transform:uppercase;letter-spacing:0.05em;">
            Sources
          </h3>
          <ul style="margin:0;padding-left:20px;font-size:14px;line-height:1.6;color:#374151;">
            {sources_html}
          </ul>

          <hr style="margin:24px 0 0 0;border:none;border-top:1px solid #e5e7eb;">
        </td></tr>
        """

    return f"""\
<!DOCTYPE html>
<html>
<head><meta charset="utf-8"></head>
<body style="margin:0;padding:0;background:#f9fafb;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;">
  <table width="100%" cellpadding="0" cellspacing="0" style="background:#f9fafb;">
    <tr><td align="center" style="padding:40px 16px;">
      <table width="600" cellpadding="0" cellspacing="0" style="background:#ffffff;border-radius:8px;box-shadow:0 1px 3px rgba(0,0,0,0.1);">
        <tr><td style="padding:32px 32px 0 32px;">
          <h1 style="margin:0 0 4px 0;font-size:28px;color:#111;">
            Story Scout Briefing
          </h1>
          <p style="margin:0 0 24px 0;font-size:15px;color:#6b7280;">
            {date_str} &middot; 3 story candidates for your bio/AI Substack
          </p>
          <hr style="margin:0;border:none;border-top:2px solid #111;">
        </td></tr>

        <tr><td style="padding:0 32px;">
          <table width="100%" cellpadding="0" cellspacing="0">
            {stories_html}
          </table>
        </td></tr>

        <tr><td style="padding:32px;text-align:center;">
          <p style="margin:0;font-size:13px;color:#9ca3af;">
            Generated by Story Scout &middot; Powered by Claude
          </p>
        </td></tr>
      </table>
    </td></tr>
  </table>
</body>
</html>"""


def send_email(html_content: str, to_email: str) -> bool:
    """Send the briefing email via SendGrid."""
    api_key = os.environ.get("SENDGRID_API_KEY")
    from_email = os.environ.get("FROM_EMAIL", "scout@example.com")

    if not api_key:
        raise RuntimeError("SENDGRID_API_KEY not set in environment")

    message = Mail(
        from_email=from_email,
        to_emails=to_email,
        subject=f"Story Scout Briefing — {datetime.now().strftime('%B %d, %Y')}",
        html_content=Content("text/html", html_content),
    )

    client = SendGridAPIClient(api_key)
    response = client.send(message)

    if response.status_code not in (200, 201, 202):
        raise RuntimeError(
            f"SendGrid returned status {response.status_code}: {response.body}"
        )

    return True
